#MBR linux Makefile

VPATH = ../MBR : ../MBR/linux : ../MBR/windows : ../base : ../platform

Objects = diskPartition.cpp MBRImpl.cpp MBRImplLinux.cpp MBRImplWindows.cpp \
	  MBRFactory.cpp MBRFactoryLinux.cpp MBRFactoryWindows.cpp

Target = ReadPartition

$(Target) :
	g++ -o $(Target) $(Objects)

.PHONY : clean
clean :
	-rm $(Target) *.o
